#!/usr/bin/env python3
"""
Daily HTML Generator
Generates a simple HTML page with "Hello World" and current timestamp.
"""

import os
import json
from datetime import datetime
from pathlib import Path


def get_run_count(counter_file: str = "/var/www/daily-pipeline/.run_count.json") -> int:
    """
    Get and increment the run counter.
    
    Args:
        counter_file: Path to the counter file
        
    Returns:
        The current run number
    """
    counter_path = Path(counter_file)
    
    # Ensure directory exists
    counter_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Read existing count or start at 1
    if counter_path.exists():
        try:
            with open(counter_path, 'r') as f:
                data = json.load(f)
                count = data.get('count', 0) + 1
        except (json.JSONDecodeError, KeyError):
            count = 1
    else:
        count = 1
    
    # Write updated count
    with open(counter_path, 'w') as f:
        json.dump({'count': count}, f)
    
    return count


def generate_html(output_path: str = "/var/www/daily-pipeline/index.html") -> None:
    """
    Generate HTML file with current timestamp and run count.
    
    Args:
        output_path: Path where the HTML file will be saved
    """
    # Get current timestamp in YYMMDD_HHMMSS format
    timestamp = datetime.now().strftime("%y%m%d_%H%M%S")
    
    # Get run count
    run_number = get_run_count()
    
    # HTML content with styling
    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daily Pipeline - Run #{run_number}</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            margin: 0;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
        }}
        .container {{
            text-align: center;
            padding: 2rem;
            background: rgba(255, 255, 255, 0.1);
            border-radius: 20px;
            backdrop-filter: blur(10px);
            box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.37);
            max-width: 600px;
        }}
        h1 {{
            font-size: 3rem;
            margin: 0 0 1rem 0;
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);
        }}
        .timestamp {{
            font-size: 2rem;
            font-weight: 300;
            letter-spacing: 0.1rem;
            margin-top: 1rem;
            padding: 1rem;
            background: rgba(255, 255, 255, 0.2);
            border-radius: 10px;
        }}
        .run-counter {{
            font-size: 1.5rem;
            margin-top: 1.5rem;
            padding: 1rem;
            background: rgba(255, 255, 255, 0.15);
            border-radius: 10px;
            font-weight: 500;
        }}
        .run-number {{
            font-size: 2.5rem;
            font-weight: bold;
            color: #ffd700;
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);
        }}
        .footer {{
            margin-top: 2rem;
            font-size: 0.9rem;
            opacity: 0.8;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🌟 Hello World 🌟</h1>
        <div class="timestamp">{timestamp}</div>
        <div class="run-counter">
            Run Number: <span class="run-number">#{run_number}</span>
        </div>
        <div class="footer">
            Generated by Daily Pipeline<br>
            Last updated: {datetime.now().strftime("%B %d, %Y at %I:%M:%S %p")}
        </div>
    </div>
</body>
</html>
"""
    
    # Ensure output directory exists
    output_dir = Path(output_path).parent
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Write HTML file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html_content)
    
    print(f"✓ HTML generated successfully: {output_path}")
    print(f"✓ Timestamp: {timestamp}")
    print(f"✓ Run number: #{run_number}")


def main():
    """Main entry point."""
    # Use environment variable if set, otherwise use default
    output_path = os.getenv('HTML_OUTPUT_PATH', '/var/www/daily-pipeline/index.html')
    
    try:
        generate_html(output_path)
    except Exception as e:
        print(f"✗ Error generating HTML: {e}")
        raise


if __name__ == "__main__":
    main()
